version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps(docker)"
  - package-ecosystem: docker
    directory: "/docker/apache"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: docker
    directory: "/docker/php"
    schedule:
      interval: weekly
      day: monday
      time: "06:45"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps(docker)"
